[package]
name = "search"
version = "0.1.0"
authors = ["Vincent Prouillet <prouillet.vincent@gmail.com>"]

[dependencies]
elasticlunr-rs = "2"
ammonia = "2"
lazy_static = "1"

errors = { path = "../errors" }
library = { path = "../library" }
