[package]
name = "templates"
version = "0.1.0"
authors = ["Vincent Prouillet <prouillet.vincent@gmail.com>"]

[dependencies]
tera = "1.0.0-beta.10"
base64 = "0.10"
lazy_static = "1"
pulldown-cmark = "0.5"
toml = "0.5"
csv = "1"
image = "0.21"
serde_json = "1.0"
reqwest = "0.9"
url = "1.5"

errors = { path = "../errors" }
utils = { path = "../utils" }
library = { path = "../library" }
config = { path = "../config" }
imageproc = { path = "../imageproc" }
